spring.application.name=starter

#BD
spring.datasource.url=jdbc:postgresql://localhost:5434/errorDB
spring.datasource.username=shopogolik
spring.datasource.password=freak

#Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.aop.auto=true

#Migration
spring.liquibase.change-log=classpath:liquibase/starter-changelog-master.yml

#Kafka
spring.kafka.bootstrap-servers=localhost:9092

#Custom dependencies
limit.method.time=100

