-- liquibase formatted sql

--changeset IvanTyapkin:1
CREATE TABLE time_limit_exceed_log(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    method_signature TEXT,
    difference BIGINT,
    units_of_measurements VARCHAR(50)
);

--changeset IvanTyapkin:2
CREATE TABLE data_source_error_log(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message VARCHAR(128),
    method_signature TEXT,
    stack_trace TEXT
);

--changeset IvanTyapkin:3
CREATE INDEX dataErrorId_index on data_source_error_log(id);