spring.application.name=2ndMicroservice
server.port=8081

#Kafka properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=transaction-group
spring.kafka.consumer.auto-offset-reset=earliest

jwt.secret.key=MMnfV1ugOrJfKQdyxT2EUigDiUu9fF2QwM9V9r/MPEEdOnBxtIlEJ6AV+tKykcwYFRozRTD60vk9j6RG3wD2cA==


# Custom Configuration
transaction.limit.count=5
transaction.limit.time.seconds=60