spring.application.name=intensiv
#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/transactions
spring.datasource.username=shopogolik
spring.datasource.password=freak
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.aop.auto=true

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=5000ms

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-lived=3600

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

#Custom config
limit.method.time=100
transaction.limit.count=5
transaction.limit.time.seconds=60

#Security
jwt.secret.key=MMnfV1ugOrJfKQdyxT2EUigDiUu9fF2QwM9V9r/MPEEdOnBxtIlEJ6AV+tKykcwYFRozRTD60vk9j6RG3wD2cA==
jwt.expiration.time.seconds=864000

#Kafka
spring.kafka.bootstrap-servers=localhost:9092